api_lessons_get_single:
    path: /api/lessons/{lessonId}
    methods: GET
    controller: App\Controller\ApiLessonsController::getSingleLesson

api_lessons_set_completed:
    path: /api/lessons/{lessonId}/progress
    methods: PUT
    controller: App\Controller\ApiLessonsController::setProgress
