App\Entity\Course:
    attributes:
        id:
            groups: ['list_courses', 'course_details', 'course_modules', 'lesson_details', 'user_details']
        title:
            groups: ['list_courses', 'course_details', 'course_modules', 'lesson_details', 'user_details']
        description:
            groups: ['list_courses', 'course_details', 'course_modules', 'lesson_details']
        coverImageName:
            groups: ['course_details']
        created:
            groups: ['course_details']
        updated:
            groups: ['course_details']
        visible:
            groups: ['course_details']
        startDate:
            groups: ['list_courses', 'course_details']
        endDate:
            groups: ['list_courses', 'course_details']
        active:
            groups: ['list_courses', 'course_details']
        authors:
            groups: ['list_courses', 'course_details']
        type:
            groups: ['list_courses', 'course_details', 'course_modules',]
        purchaseUrl:
            groups: ['list_courses', 'course_details', 'course_modules',]
        parent:
            groups: ['list_courses', 'course_details']
