api_login_check:
    path: /api/login_check

admin_logout:
    path: /admin/logout
    methods: GET

admin_login:
    path: /admin/login
    methods: GET
    controller: App\Controller\AdminSecurityController::login

admin_settings:
    path: /admin/settings
    methods: GET|POST
    controller: App\Controller\AdminSettingsController::index
