App\Entity\Bookmark:
    type: entity
    repositoryClass: App\Repository\BookmarkRepository
    table: npd_bookmark
    id:
        id:
            column: uuid
            type: uuid
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        title:
            type: string
            length: 255
        timeInSeconds:
            type: integer
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        user:
            targetEntity: App\Entity\User
            joinColumn:
                name: user_uuid
                referencedColumnName: uuid
                nullable: true
        lesson:
            targetEntity: App\Entity\Lesson
            joinColumn:
                name: lesson_uuid
                referencedColumnName: uuid
                nullable: false
